import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  AppWindow,
  Axe,
  Blocks,
  BookMarked,
  BookOpen,
  Box,
  Brain,
  Brush,
  Building2,
  Calendar,
  Castle,
  CircleDot,
  Clapperboard,
  Code2,
  Coffee,
  Coins,
  Compass,
  Component,
  Cpu,
  Crosshair,
  Crown,
  Database,
  Dices,
  Drama,
  Eye,
  Factory,
  FileText,
  Film,
  Flag,
  Flame,
  FolderTree,
  Gamepad2,
  Gauge,
  Gem,
  GitBranch,
  Globe,
  Grid3x3,
  Hammer,
  HardDrive,
  Heart,
  Hexagon,
  Home,
  Image,
  KeyRound,
  Landmark,
  Layers,
  Layout,
  Leaf,
  Library,
  Lightbulb,
  ListChecks,
  Map,
  MapPin,
  MessageCircle,
  Monitor,
  Moon,
  Mountain,
  MousePointer2,
  Music,
  Network,
  Notebook,
  Orbit,
  Package,
  Palette,
  PanelTop,
  PenLine,
  Pencil,
  Play,
  Puzzle,
  Radar,
  Repeat,
  Rocket,
  Route,
  Scale,
  ScrollText,
  Search,
  Server,
  Settings2,
  Shapes,
  Shield,
  Ship,
  Skull,
  Smartphone,
  Sparkles,
  Star,
  StickyNote,
  Store,
  Swords,
  Target,
  Tent,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  UserCog,
  Wand2,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Stable icon keys used across Project Brain (wizards, blobs, guidance).
 * Values are Lucide component names — not emoji, not uploaded assets.
 */
export const ICON_KEYS = [
  "gamepad",
  "swords",
  "skull",
  "book",
  "coffee",
  "tent",
  "package",
  "building",
  "cpu",
  "dices",
  "map",
  "castle",
  "puzzle",
  "crosshair",
  "users",
  "box",
  "shield",
  "sparkles",
  "code",
  "smartphone",
  "palette",
  "layers",
  "pencil",
  "bookmark",
  "trending",
  "globe",
  "cog",
  "settings",
  "scroll",
  "home",
  "hammer",
  "alert",
  "coins",
  "layout",
  "file",
  "calendar",
  "wrench",
  "clapperboard",
  "repeat",
  "zap",
  "key",
  "flag",
  "list-checks",
  "monitor",
  "grid",
  "message",
  "wand",
  "blocks",
  "network",
  "pointer",
  "server",
  "hard-drive",
  "panel",
  "git-branch",
  "component",
  "database",
  "app-window",
  "lightbulb",
  "image",
  "circle-dot",
  "search",
  "sticky-note",
  "folder-tree",
  "play",
  "pen",
  "eye",
  "shapes",
  "target",
  "heart",
  "flame",
  "mountain",
  "music",
  "brush",
  "star",
  "hexagon",
  "orbit",
  "radar",
  "compass",
  "axe",
  "crown",
  "gem",
  "leaf",
  "moon",
  "ship",
  "factory",
  "store",
  "landmark",
  "map-pin",
  "route",
  "waypoints",
  "library",
  "notebook",
  "drama",
  "film",
  "trophy",
  "timer",
  "gauge",
  "scale",
  "activity",
  "brain",
  "rocket",
  "workflow",
  "user-cog",
] as const;

export type IconKey = (typeof ICON_KEYS)[number];

export function isIconKey(value: string): value is IconKey {
  return (ICON_KEYS as readonly string[]).includes(value);
}

/** Lucide components for every catalog key. */
export const ICON_COMPONENTS: Record<IconKey, LucideIcon> = {
  gamepad: Gamepad2,
  swords: Swords,
  skull: Skull,
  book: BookOpen,
  coffee: Coffee,
  tent: Tent,
  package: Package,
  building: Building2,
  cpu: Cpu,
  dices: Dices,
  map: Map,
  castle: Castle,
  puzzle: Puzzle,
  crosshair: Crosshair,
  users: Users,
  box: Box,
  shield: Shield,
  sparkles: Sparkles,
  code: Code2,
  smartphone: Smartphone,
  palette: Palette,
  layers: Layers,
  pencil: Pencil,
  bookmark: BookMarked,
  trending: TrendingUp,
  globe: Globe,
  cog: Settings2,
  settings: Settings2,
  scroll: ScrollText,
  home: Home,
  hammer: Hammer,
  alert: AlertTriangle,
  coins: Coins,
  layout: Layout,
  file: FileText,
  calendar: Calendar,
  wrench: Wrench,
  clapperboard: Clapperboard,
  repeat: Repeat,
  zap: Zap,
  key: KeyRound,
  flag: Flag,
  "list-checks": ListChecks,
  monitor: Monitor,
  grid: Grid3x3,
  message: MessageCircle,
  wand: Wand2,
  blocks: Blocks,
  network: Network,
  pointer: MousePointer2,
  server: Server,
  "hard-drive": HardDrive,
  panel: PanelTop,
  "git-branch": GitBranch,
  component: Component,
  database: Database,
  "app-window": AppWindow,
  lightbulb: Lightbulb,
  image: Image,
  "circle-dot": CircleDot,
  search: Search,
  "sticky-note": StickyNote,
  "folder-tree": FolderTree,
  play: Play,
  pen: PenLine,
  eye: Eye,
  shapes: Shapes,
  target: Target,
  heart: Heart,
  flame: Flame,
  mountain: Mountain,
  music: Music,
  brush: Brush,
  star: Star,
  hexagon: Hexagon,
  orbit: Orbit,
  radar: Radar,
  compass: Compass,
  axe: Axe,
  crown: Crown,
  gem: Gem,
  leaf: Leaf,
  moon: Moon,
  ship: Ship,
  factory: Factory,
  store: Store,
  landmark: Landmark,
  "map-pin": MapPin,
  route: Route,
  waypoints: Waypoints,
  library: Library,
  notebook: Notebook,
  drama: Drama,
  film: Film,
  trophy: Trophy,
  timer: Timer,
  gauge: Gauge,
  scale: Scale,
  activity: Activity,
  brain: Brain,
  rocket: Rocket,
  workflow: Workflow,
  "user-cog": UserCog,
};

/** Curated subset shown in the blob icon picker (scan-friendly, not the full set). */
export const PICKER_ICON_KEYS: readonly IconKey[] = [
  "shapes",
  "folder-tree",
  "gamepad",
  "swords",
  "shield",
  "skull",
  "book",
  "bookmark",
  "scroll",
  "globe",
  "map",
  "compass",
  "users",
  "user-cog",
  "heart",
  "flame",
  "target",
  "crosshair",
  "puzzle",
  "dices",
  "castle",
  "crown",
  "gem",
  "zap",
  "cog",
  "settings",
  "workflow",
  "network",
  "cpu",
  "code",
  "smartphone",
  "palette",
  "brush",
  "image",
  "film",
  "drama",
  "music",
  "lightbulb",
  "sparkles",
  "wand",
  "star",
  "trophy",
  "flag",
  "home",
  "building",
  "factory",
  "store",
  "tent",
  "mountain",
  "leaf",
  "moon",
  "coffee",
  "coins",
  "package",
  "box",
  "blocks",
  "layers",
  "layout",
  "panel",
  "monitor",
  "grid",
  "database",
  "server",
  "hard-drive",
  "component",
  "git-branch",
  "route",
  "waypoints",
  "map-pin",
  "landmark",
  "key",
  "hammer",
  "wrench",
  "axe",
  "alert",
  "activity",
  "gauge",
  "scale",
  "timer",
  "repeat",
  "trending",
  "calendar",
  "list-checks",
  "file",
  "notebook",
  "library",
  "sticky-note",
  "search",
  "eye",
  "pen",
  "pencil",
  "play",
  "message",
  "clapperboard",
  "brain",
  "rocket",
  "orbit",
  "radar",
  "hexagon",
  "circle-dot",
  "app-window",
  "pointer",
] as const;
