import type { NodeType, ProjectType } from "@/types";
import type { IconKey } from "./catalog";

/** Project type cards in the create-project wizard. */
export const PROJECT_TYPE_ICONS: Record<ProjectType, IconKey> = {
  GAME: "gamepad",
  SOFTWARE: "code",
  APP: "smartphone",
  CREATIVE: "palette",
  OTHER: "layers",
  CUSTOM: "pencil",
};

/** Genre template keys → default icon. */
export const GENRE_ICONS: Record<string, IconKey> = {
  "action-rpg": "swords",
  soulslike: "skull",
  "narrative-adventure": "book",
  cozy: "coffee",
  survival: "tent",
  "resource-management": "package",
  management: "building",
  simulation: "cpu",
  roguelike: "dices",
  metroidvania: "map",
  strategy: "castle",
  puzzle: "puzzle",
  shooter: "crosshair",
  "party-game": "users",
  sandbox: "box",
  rpg: "shield",
  custom: "sparkles",
};

/**
 * Structural Project Area / Design Focus names → icon.
 * Matched case-insensitively (exact, then includes).
 */
export const NAME_ICONS: Record<string, IconKey> = {
  // Game / shared areas
  story: "bookmark",
  combat: "swords",
  progression: "trending",
  world: "globe",
  characters: "users",
  character: "users",
  mechanics: "cog",
  systems: "settings",
  lore: "scroll",
  activities: "sparkles",
  base: "home",
  crafting: "hammer",
  threats: "alert",
  economy: "coins",
  ui: "layout",
  content: "file",
  facilities: "building",
  staff: "user-cog",
  events: "calendar",
  tools: "wrench",
  scenarios: "clapperboard",
  runs: "repeat",
  meta: "layers",
  abilities: "zap",
  secrets: "key",
  factions: "flag",
  map: "map",
  puzzles: "puzzle",
  rules: "list-checks",
  presentation: "monitor",
  minigames: "gamepad",
  modes: "grid",
  social: "message",
  creation: "wand",
  weapons: "crosshair",
  levels: "layers",
  // Non-game areas
  features: "blocks",
  architecture: "network",
  ux: "pointer",
  backend: "server",
  infrastructure: "hard-drive",
  screens: "panel",
  flows: "git-branch",
  components: "component",
  data: "database",
  platform: "app-window",
  concepts: "lightbulb",
  chapters: "book",
  visuals: "image",
  themes: "sparkles",
  theme: "sparkles",
  core: "circle-dot",
  research: "search",
  deliverables: "package",
  notes: "sticky-note",
  structure: "folder-tree",
  details: "list-checks",
  // Common design focuses
  "combat feel": "swords",
  "character progression": "trending",
  exploration: "compass",
  "loot & rewards": "gem",
  "world building": "globe",
  "quest design": "flag",
  "difficulty curve": "gauge",
  "combat mastery": "target",
  "boss design": "crown",
  "risk / reward": "scale",
  "level design & shortcuts": "route",
  "atmosphere & tone": "moon",
  "death / recovery loop": "repeat",
  "cryptic narrative": "scroll",
  "build variety": "layers",
  "narrative arc": "bookmark",
  "character development": "users",
  "player choice / agency": "compass",
  "themes & motifs": "sparkles",
  "pacing & structure": "timer",
  "environmental storytelling": "landmark",
  usability: "pointer",
  reliability: "shield",
  maintainability: "wrench",
  performance: "gauge",
  extensibility: "git-branch",
  "user experience": "smartphone",
  clarity: "eye",
  retention: "heart",
  accessibility: "users",
  "emotional impact": "heart",
  pacing: "timer",
  craft: "brush",
  originality: "sparkles",
  coherence: "network",
  impact: "zap",
  feasibility: "scale",
};

/** Project Structure node types → fallback icon. */
export const NODE_TYPE_ICONS: Record<NodeType, IconKey> = {
  FOLDER: "folder-tree",
  MECHANIC: "cog",
  CHARACTER: "users",
  QUEST: "flag",
  LOCATION: "map-pin",
  STORY_BEAT: "bookmark",
  SYSTEM: "settings",
  ITEM: "package",
  FACTION: "flag",
  UI_SCREEN: "panel",
  IDEA: "lightbulb",
  TASK: "list-checks",
  ACT: "clapperboard",
  CUSTOM: "shapes",
};

/** Guidance dashboard opportunity kinds. */
export const GUIDANCE_KIND_ICONS: Record<
  "continue" | "fill_in" | "review" | "continue_structure",
  IconKey
> = {
  continue: "play",
  fill_in: "pen",
  review: "eye",
  continue_structure: "folder-tree",
};
